# -- coding: utf-8 --

# Form implementation generated from reading ui file 'GUITarea.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 530)
        self.NombreArchivo = QtWidgets.QLabel(Dialog)
        self.NombreArchivo.setGeometry(QtCore.QRect(250, 50, 131, 41))
        self.NombreArchivo.setObjectName("NombreArchivo")
        self.TextoAEscribir = QtWidgets.QLabel(Dialog)
        self.TextoAEscribir.setGeometry(QtCore.QRect(250, 120, 131, 41))
        self.TextoAEscribir.setObjectName("TextoAEscribir")
        self.NumeorDeLineasEnArchivo = QtWidgets.QLabel(Dialog)
        self.NumeorDeLineasEnArchivo.setGeometry(QtCore.QRect(250, 190, 171, 41))
        self.NumeorDeLineasEnArchivo.setObjectName("NumeorDeLineasEnArchivo")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 280, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.NumeroDeVocales = QtWidgets.QLabel(Dialog)
        self.NumeroDeVocales.setGeometry(QtCore.QRect(20, 370, 131, 41))
        self.NumeroDeVocales.setObjectName("NumeroDeVocales")
        self.NumeroDeConsonantes = QtWidgets.QLabel(Dialog)
        self.NumeroDeConsonantes.setGeometry(QtCore.QRect(290, 370, 151, 41))
        self.NumeroDeConsonantes.setObjectName("NumeroDeConsonantes")
        self.NombreA = QtWidgets.QLineEdit(Dialog)
        self.NombreA.setGeometry(QtCore.QRect(40, 60, 113, 22))
        self.NombreA.setObjectName("NombreA")
        self.TextoAE = QtWidgets.QLineEdit(Dialog)
        self.TextoAE.setGeometry(QtCore.QRect(40, 130, 113, 22))
        self.TextoAE.setObjectName("TextoAE")
        self.TextoAE_2 = QtWidgets.QLineEdit(Dialog)
        self.TextoAE_2.setGeometry(QtCore.QRect(40, 200, 113, 22))
        self.TextoAE_2.setObjectName("TextoAE_2")
        self.NumeroV = QtWidgets.QLineEdit(Dialog)
        self.NumeroV.setGeometry(QtCore.QRect(20, 420, 113, 22))
        self.NumeroV.setObjectName("NumeroV")
        self.NumeroC = QtWidgets.QLineEdit(Dialog)
        self.NumeroC.setGeometry(QtCore.QRect(300, 420, 113, 22))
        self.NumeroC.setObjectName("NumeroC")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.NombreArchivo.setText(_translate("Dialog", "Nombre del Archivo"))
        self.TextoAEscribir.setText(_translate("Dialog", "Texto A Escribir"))
        self.NumeorDeLineasEnArchivo.setText(_translate("Dialog", "Numero de lineas en archivo"))
        self.pushButton.setText(_translate("Dialog", "Analizar"))
        self.NumeroDeVocales.setText(_translate("Dialog", "Numero de Vocales"))
        self.NumeroDeConsonantes.setText(_translate("Dialog", "Numero de Consonantes"))


if _name_ == "_main_":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
